### ISSUE TITLE
Wrong log file name in debian/logrotate

### ISSUE THREAD

**Issue by schragge** [elmar/aptitude-robot#12]
Default log file name in `debian/default` is `/var/log/aptitude-robot.log`, but `debian/logrotate` specifies `/var/log/aptitude-robot` (without the `.log` extension) which results in:
```
rotating pattern: /var/log/aptitude-robot  monthly (6 rotations)
empty log files are not rotated, old logs are removed
switching euid to 0 and egid to 4
considering log /var/log/aptitude-robot
  log /var/log/aptitude-robot does not exist -- skipping
switching euid to 0 and egid to 0
```

**Comment by xtaran** [comment]
Indeed, thanks for that bug report1 (And sorry that I oversaw it when you filed it.)
