### ISSUE TITLE
wrong options with later aptitude

### ISSUE THREAD

**Issue by alexmyczko** [elmar/aptitude-robot#9]
from a certain aptitude on, I keep getting:
W: --force-yes is deprecated, use one of the options starting with --allow instead.

**Comment by xtaran** [comment]
JFTR: The error message doesn't come from aptitude but from apt:

```
apt-private/private-cmndline.cc:      _error->Warning(_("--force-yes is deprecated, use one of the options starting with --allow instead."));
```

**Comment by xtaran** [comment]
I suspect it might come from an APT hook of another package you're using. Does it still appear?

If so: Please do an `dpkg -S /etc/apt/apt.conf.d` on that host and do a `dfgrep force-yes` (from the `debian-goodies` package) with all packages listed by the previous command except `apt` itself. Example from the one host where I can login in your organization:

```
→ dpkg -S /etc/apt/apt.conf.d
command-not-found, hobbit-plugins, apt-file, debconf, apt-show-versions, apt: /etc/apt/apt.conf.d
→ dfgrep force-yes command-not-found hobbit-plugins apt-file debconf apt-show-versions 
grep: /etc/sudoers.d/xymon: Permission denied
```

So on that host, none of the package in questions seems to use `--force-yes` (anymore).

**Comment by alexmyczko** [comment]
report being from 2018, the answer to previous questions i negative (4 years later)
